# Generated by Django 2.2.12 on 2020-05-15 12:59

import functools

import django.utils.timezone
from django.db import migrations, models

import confirmed_contact.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfirmedContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="The ID of this entry on the external system. Used "
                        "for deduplication",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "msisdn",
                    models.CharField(
                        help_text="MSISDN of the confirmed contact",
                        max_length=255,
                        validators=[
                            functools.partial(
                                confirmed_contact.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp of when contact was confirmed",
                    ),
                ),
                (
                    "set_active",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        editable=False,
                        help_text="Whether the contact has been set to active in Turn",
                    ),
                ),
                (
                    "set_inactive",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        editable=False,
                        help_text="Whether the contact has been set to inactive in "
                        "Turn",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the confirmed contact",
                        max_length=255,
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Case ID of the confirmation",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Django username who created this", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this was added to the database",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="confirmedcontact",
            index=models.Index(
                fields=["msisdn", "-timestamp"], name="confirmed_c_msisdn_6c33b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="confirmedcontact",
            index=models.Index(
                condition=models.Q(set_active=False),
                fields=["set_active"],
                name="active_false_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="confirmedcontact",
            index=models.Index(
                condition=models.Q(set_inactive=False),
                fields=["set_inactive", "timestamp"],
                name="inactive_false_idx",
            ),
        ),
    ]
