# Generated by Django 2.2.13 on 2020-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_auto_20200721_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="external_id",
            field=models.CharField(
                default="714b7fddc1ca4bca8b42a817d50353d0", max_length=255
            ),
        ),
    ]
