# Generated by Django 2.2.13 on 2020-07-22 08:08

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_auto_20200722_0806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="external_id",
            field=models.CharField(default=contacts.models.get_uuid, max_length=255),
        ),
    ]
