# Generated by Django 2.2.13 on 2020-07-22 10:33

import contacts.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_auto_20200722_0808"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="date_notification",
            new_name="date_notification_end",
        ),
        migrations.AddField(
            model_name="case",
            name="date_notification_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="external_id",
            field=models.CharField(
                default=contacts.models.get_uuid, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="msisdn",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
