# Generated by Django 3.1.13 on 2021-11-03 08:53

from django.db import migrations


def create_permission_class(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    content_type = ContentType.objects.using(db_alias).create(
        app_label="vaxchamps", model="registration"
    )
    Permission.objects.using(db_alias).create(
        codename="create_registration",
        name="Create registration",
        content_type=content_type,
    )


def delete_permission_class(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    Permission.objects.using(db_alias).filter(
        codename="create_registration", name="Create registration"
    ).delete()
    ContentType.objects.using(db_alias).filter(
        app_label="vaxchamps", model="registration"
    ).delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_permission_class, delete_permission_class)
    ]
