# Generated by Django 3.1.13 on 2021-12-10 13:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid_cases", "0002_auto_20211210_1304"),
    ]

    operations = [
        migrations.CreateModel(
            name="SACoronavirusCaseImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="The original URL of the image")),
                ("image", models.ImageField(help_text="The cases image", upload_to="")),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, help_text="The day the data is for"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this was added to the database",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this was last updated"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sacoronaviruscaseimage",
            constraint=models.UniqueConstraint(fields=("url",), name="unique_image"),
        ),
    ]
