# Generated by Django 3.1.14 on 2022-06-13 07:12

from django.db import migrations, models
import django.utils.timezone
import django_prometheus.models
import functools
import userprofile.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TBCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deduplication_id",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "msisdn",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ZA-EC", "Eastern Cape"),
                            ("ZA-FS", "Free State"),
                            ("ZA-GT", "Gauteng"),
                            ("ZA-LP", "Limpopo"),
                            ("ZA-MP", "Mpumalanga"),
                            ("ZA-NC", "Northern Cape"),
                            ("ZA-NL", "Kwazulu-Natal"),
                            ("ZA-NW", "North-West (South Africa)"),
                            ("ZA-WC", "Western Cape"),
                        ],
                        max_length=6,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("<18", "<18"),
                            ("18-40", "18-40"),
                            ("40-65", "40-65"),
                            (">65", ">65"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_say", "Rather not say"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=255,
                        null=True,
                        validators=[userprofile.validators.geographic_coordinate],
                    ),
                ),
                (
                    "city_location",
                    models.CharField(
                        max_length=255,
                        null=True,
                        validators=[userprofile.validators.geographic_coordinate],
                    ),
                ),
                ("cough", models.BooleanField()),
                ("fever", models.BooleanField()),
                ("sweat", models.BooleanField()),
                ("weight", models.BooleanField()),
                (
                    "exposure",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "tracing",
                    models.BooleanField(
                        help_text="Whether the NDoH can contact the user"
                    ),
                ),
                (
                    "completed_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=22,
                    ),
                ),
                ("follow_up_optin", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("eng", "English"),
                            ("zul", "isiZulu"),
                            ("afr", "Afrikaans"),
                            ("xho", "isiXhosa"),
                            ("sot", "Sesotho"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "commit_get_tested",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("research_consent", models.BooleanField(null=True)),
                (
                    "originating_msisdn",
                    models.CharField(
                        max_length=255,
                        null=True,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("activation", models.CharField(max_length=255, null=True)),
                (
                    "clinic_to_visit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "clinic_visit_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
            ],
            # bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
        migrations.CreateModel(
            name="TBTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deduplication_id",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            # bases=(django_prometheus.models.ExportModelOperationsMixin.<locals>.Mixin, models.Model),
        ),
    ]
