# Generated by Django 3.1.14 on 2022-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbcheck",
            name="research_consent",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
