# Generated by Django 3.1 on 2020-08-26 10:43

from django.db import migrations, models

import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbcheck",
            name="city_location",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[userprofile.validators.geographic_coordinate],
            ),
        ),
        migrations.AlterField(
            model_name="tbcheck",
            name="location",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[userprofile.validators.geographic_coordinate],
            ),
        ),
    ]
