# Generated by Django 3.1 on 2020-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0002_update_tbcheck_location_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbcheck",
            name="follow_up_optin",
            field=models.BooleanField(default=False),
        ),
    ]
