# Generated by Django 3.1 on 2020-09-02 12:36

import functools

import django.utils.timezone
from django.db import migrations, models

import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0004_tbcheck_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbcheck",
            name="msisdn",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    functools.partial(
                        userprofile.validators._phone_number, *(), **{"country": "ZA"}
                    )
                ],
            ),
        ),
    ]
