# Generated by Django 3.1 on 2020-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0005_auto_20200902_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbcheck", name="cough", field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="tbcheck",
            name="risk",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                max_length=22,
            ),
        ),
    ]
