# Generated by Django 3.1 on 2020-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0007_tbtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbtest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
