# Generated by Django 3.1.12 on 2021-06-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0008_tbtest_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbcheck",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
