# Generated by Django 3.1.14 on 2022-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0009_tbcheck_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbcheck",
            name="commit_get_tested",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tbcheck",
            name="group_arm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("control", "Control"),
                    ("health_consequence", "Health Consequence"),
                    ("planning_prompt", "Planning Prompt"),
                    ("soft_commitment", "Soft Commitment"),
                    ("soft_commitment_plus", "Soft Commitment Plus"),
                ],
                max_length=22,
                null=True,
            ),
        ),
    ]
