# Generated by Django 3.1.14 on 2022-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0012_tbcheck_research_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbcheck",
            name="research_consent",
            field=models.BooleanField(default=False),
        ),
    ]
