# Generated by Django 3.1.14 on 2022-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbconnect', '0013_auto_20220511_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcheck',
            name='research_consent',
            field=models.BooleanField(),
        ),
    ]
