# Generated by Django 3.1.14 on 2023-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tbconnect", "0014_auto_20220615_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbcheck",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eng", "English"),
                    ("zul", "isiZulu"),
                    ("afr", "Afrikaans"),
                    ("xho", "isiXhosa"),
                    ("sot", "Sesotho"),
                    ("set", "Setswana"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
