# Generated by Django 3.1 on 2020-10-21 07:06

from django.db import migrations, models
import django.utils.timezone
import functools
import userprofile.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfSwabScreen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('contact_id', models.CharField(max_length=255)),
                ('msisdn', models.CharField(db_index=True, max_length=255, validators=[functools.partial(userprofile.validators._phone_number, *(), **{'country': 'ZA'})])),
                ('registration', models.CharField(blank=True, choices=[('incomplete', 'incomplete'), ('complete', 'complete')], max_length=20)),
                ('age', models.CharField(choices=[('<18', '<18'), ('18-40', '18-40'), ('40-65', '40-65'), ('>65', '>65')], max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_say', 'Rather not say')], max_length=10)),
                ('facility', models.CharField(max_length=255)),
                ('risk_type', models.CharField(choices=[('Low', 'Low'), ('High', 'High')], max_length=10)),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('employee_number', models.CharField(blank=True, default='', max_length=10)),
                ('pre_existing_condition', models.CharField(blank=True, default='', max_length=255)),
                ('cough', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('shortness_of_breath', models.BooleanField()),
                ('body_aches', models.BooleanField()),
                ('loss_of_taste_smell', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('additional_symptoms', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SelfSwabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('contact_id', models.CharField(max_length=255)),
                ('msisdn', models.CharField(db_index=True, max_length=255, validators=[functools.partial(userprofile.validators._phone_number, *(), **{'country': 'ZA'})])),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Rejected', 'Rejected'), ('Equivocal', 'Equivocal'), ('Inconclusive', 'Inconclusive'), ('Indeterminate', 'Indeterminate'), ('Invalid', 'Invalid')], max_length=100)),
                ('barcode', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
