# Generated by Django 3.1 on 2020-10-20 07:13

import functools
import uuid

import django.utils.timezone
from django.db import migrations, models

import userprofile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelfSwabRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_id", models.UUIDField()),
                (
                    "msisdn",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[("Low", "Low"), ("High", "High")], max_length=10
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
