# Generated by Django 3.1 on 2020-10-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfswabscreen",
            name="age",
            field=models.CharField(
                choices=[
                    ("<18", "<18"),
                    ("18-39", "18-39"),
                    ("40-65", "40-65"),
                    (">65", ">65"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="selfswabscreen",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("not_say", "not_say"),
                ],
                max_length=10,
            ),
        ),
    ]
