# Generated by Django 3.1 on 2020-10-20 10:58

import functools
import uuid

import django.utils.timezone
from django.db import migrations, models

import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfSwabScreen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_id", models.CharField(max_length=255)),
                (
                    "msisdn",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "registration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incomplete", "incomplete"),
                            ("complete", "complete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("<18", "<18"),
                            ("18-40", "18-40"),
                            ("40-65", "40-65"),
                            (">65", ">65"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_say", "Rather not say"),
                        ],
                        max_length=10,
                    ),
                ),
                ("facility", models.CharField(max_length=255)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[("Low", "Low"), ("High", "High")], max_length=10
                    ),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "employee_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "pre_existing_condition",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cough", models.BooleanField()),
                ("fever", models.BooleanField()),
                ("shortness_of_breath", models.BooleanField()),
                ("body_aches", models.BooleanField()),
                ("loss_of_taste_smell", models.BooleanField()),
                ("sore_throat", models.BooleanField()),
                ("additional_symptoms", models.BooleanField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfSwabTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_id", models.CharField(max_length=255)),
                (
                    "msisdn",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("positive", "positive"),
                            ("negative", "negative"),
                        ],
                        max_length=10,
                    ),
                ),
                ("barcode", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(name="SelfSwabRegistration",),
    ]
