# Generated by Django 3.1 on 2020-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0002_auto_20201020_1258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfswabtest",
            name="result",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Rejected", "Rejected"),
                    ("Equivocal", "Equivocal"),
                    ("Inconclusive", "Inconclusive"),
                    ("Indeterminate", "Indeterminate"),
                    ("Invalid", "Invalid"),
                ],
                max_length=100,
            ),
        ),
    ]
