# Generated by Django 3.1 on 2020-10-28 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0002_auto_20201023_0846"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfSwabRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                (
                    "employee_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "contact_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("facility", models.CharField(max_length=255)),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
    ]
