# Generated by Django 3.1 on 2020-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0004_auto_20201029_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfswabtest",
            name="barcode",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
