# Generated by Django 3.1 on 2020-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0004_auto_20201029_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfswabtest",
            name="authorized_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="selfswabtest",
            name="collection_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="selfswabtest",
            name="received_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
