# Generated by Django 3.1 on 2020-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0005_auto_20201102_1623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfswabtest",
            name="result",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Rejected", "Rejected"),
                    ("Invalid", "Invalid"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
