# Generated by Django 3.1 on 2020-11-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0005_auto_20201109_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfswabtest",
            name="authorized_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="selfswabtest",
            name="collection_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="selfswabtest",
            name="received_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="selfswabtest",
            name="result",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Rejected", "Rejected"),
                    ("Invalid", "Invalid"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
