# Generated by Django 3.1 on 2020-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0008_auto_20201126_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selfswabscreen",
            name="employee_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
