# Generated by Django 3.1 on 2020-12-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0010_selfswabscreen_should_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfswabtest",
            name="should_sync",
            field=models.BooleanField(default=True),
        ),
    ]
