# Generated by Django 3.1 on 2020-12-03 06:28

from django.conf import settings
from django.db import migrations

from temba_client.v2 import TembaClient


def clean_gender(gender):
    if gender in ("O", "other"):
        gender = "Other"
    elif gender == "Not say":
        gender = "not_say"

    return gender


def should_sync_contact(contact):
    for group in contact.groups:
        if "test" in group.name.lower():
            return False
    return True


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0012_auto_20201202_1235"),
    ]

    def update_rapidpro_contacts_registration_id(apps, schema_editor):
        SelfSwabRegistration = apps.get_model("selfswab", "SelfSwabRegistration")

        rapidpro = TembaClient(settings.RAPIDPRO_URL, settings.SELFSWAB_RAPIDPRO_TOKEN)

        for contact_batch in rapidpro.get_contacts().iterfetches(
            retry_on_rate_exceed=True
        ):
            for contact in contact_batch:
                if contact.fields["contact_pid"]:
                    registration = SelfSwabRegistration.objects.filter(
                        contact_id=contact.fields["contact_pid"]
                    ).first()

                    if registration:
                        rapidpro.update_contact(
                            contact,
                            fields={"self_swab_registration_id": str(registration.id)},
                        )

                        registration.age = contact.fields.get("age")
                        registration.gender = clean_gender(contact.fields.get("gender"))
                        registration.should_sync = should_sync_contact(contact)
                        registration.save()

    operations = [
        migrations.RunPython(update_rapidpro_contacts_registration_id),
    ]
