# Generated by Django 3.1 on 2020-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0013_update_rapidpro_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfswabregistration",
            name="opted_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="selfswabregistration",
            name="optout_reason",
            field=models.CharField(
                choices=[
                    (
                        "reminders",
                        "I no longer want to receive weekly screening reminders",
                    ),
                    (
                        "tested_positive",
                        "I have tested positive for COVID-19, and so can no longer be part of the study",
                    ),
                    ("other", "Other"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="selfswabregistration",
            name="optout_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
