# Generated by Django 3.1 on 2020-12-08 13:03

from django.db import migrations, models
import functools
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0014_auto_20201204_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfswabregistration",
            name="msisdn",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    functools.partial(
                        userprofile.validators._phone_number, *(), **{"country": "ZA"}
                    )
                ],
            ),
        ),
    ]
