# Generated by Django 3.1 on 2020-12-08 13:06

from django.conf import settings
from django.db import migrations

from temba_client.v2 import TembaClient


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0015_selfswabregistration_msisdn"),
    ]

    def update_registrations_msisdn(apps, schema_editor):
        SelfSwabRegistration = apps.get_model("selfswab", "SelfSwabRegistration")

        if not settings.RAPIDPRO_URL or not settings.SELFSWAB_RAPIDPRO_TOKEN:
            return

        rapidpro = TembaClient(settings.RAPIDPRO_URL, settings.SELFSWAB_RAPIDPRO_TOKEN)

        for contact_batch in rapidpro.get_contacts().iterfetches(
            retry_on_rate_exceed=True
        ):
            for contact in contact_batch:
                if contact.fields["contact_pid"]:
                    registration = SelfSwabRegistration.objects.filter(
                        contact_id=contact.fields["contact_pid"]
                    ).first()

                    if registration:
                        registration.msisdn = contact.urns[0].split(":")[1]
                        registration.save()

    operations = [
        migrations.RunPython(update_registrations_msisdn),
    ]
