# Generated by Django 3.1 on 2021-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfswab", "0016_update_registration_msisdn"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfswabtest",
            name="pdf_media_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
