# Generated by Django 2.2.13 on 2020-08-12 17:53

import functools
import uuid

import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.db import migrations, models

import userprofile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Covid19Triage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deduplication_id",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ZA-EC", "Eastern Cape"),
                            ("ZA-FS", "Free State"),
                            ("ZA-GT", "Gauteng"),
                            ("ZA-LP", "Limpopo"),
                            ("ZA-MP", "Mpumalanga"),
                            ("ZA-NC", "Northern Cape"),
                            ("ZA-NL", "Kwazulu-Natal"),
                            ("ZA-NW", "North-West (South Africa)"),
                            ("ZA-WC", "Western Cape"),
                        ],
                        max_length=6,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("<18", "<18"),
                            ("18-40", "18-40"),
                            ("40-65", "40-65"),
                            (">65", ">65"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("fever", models.BooleanField()),
                ("cough", models.BooleanField()),
                ("sore_throat", models.BooleanField()),
                (
                    "difficulty_breathing",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "exposure",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "confirmed_contact",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "tracing",
                    models.BooleanField(
                        help_text="Whether the NDoH can contact the user"
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_say", "Rather not say"),
                        ],
                        default="",
                        max_length=7,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[userprofile.validators.geographic_coordinate],
                    ),
                ),
                (
                    "city_location",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        validators=[userprofile.validators.geographic_coordinate],
                    ),
                ),
                (
                    "muscle_pain",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("smell", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "preexisting_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        default="",
                        max_length=9,
                    ),
                ),
                (
                    "rooms_in_household",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "persons_in_household",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "completed_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthCheckUserProfile",
            fields=[
                (
                    "msisdn",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ZA-EC", "Eastern Cape"),
                            ("ZA-FS", "Free State"),
                            ("ZA-GT", "Gauteng"),
                            ("ZA-LP", "Limpopo"),
                            ("ZA-MP", "Mpumalanga"),
                            ("ZA-NC", "Northern Cape"),
                            ("ZA-NL", "Kwazulu-Natal"),
                            ("ZA-NW", "North-West (South Africa)"),
                            ("ZA-WC", "Western Cape"),
                        ],
                        max_length=6,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("<18", "<18"),
                            ("18-40", "18-40"),
                            ("40-65", "40-65"),
                            (">65", ">65"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("not_say", "Rather not say"),
                        ],
                        default="",
                        max_length=7,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        validators=[userprofile.validators.geographic_coordinate],
                    ),
                ),
                (
                    "city_location",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        validators=[userprofile.validators.geographic_coordinate],
                    ),
                ),
                (
                    "preexisting_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not_sure", "Not sure"),
                        ],
                        default="",
                        max_length=9,
                    ),
                ),
                (
                    "rooms_in_household",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "persons_in_household",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="covid19triage",
            index=models.Index(
                fields=["msisdn", "timestamp"], name="userprofile_msisdn_8da1c7_idx"
            ),
        ),
    ]
