# Generated by Django 3.1 on 2020-08-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covid19triage",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="healthcheckuserprofile",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
