# Generated by Django 3.1 on 2020-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_auto_20200814_1341"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="covid19triage",
            name="userprofile_msisdn_8da1c7_idx",
        ),
        migrations.AddIndex(
            model_name="covid19triage",
            index=models.Index(
                fields=["msisdn", "timestamp"], name="eventstore__msisdn_dbf292_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="covid19triage",
            table="eventstore_covid19triage",
        ),
        migrations.AlterModelTable(
            name="healthcheckuserprofile",
            table="eventstore_healthcheckuserprofile",
        ),
    ]
