# Generated by Django 3.1 on 2020-08-17 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_auto_20200814_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covid19triage",
            name="deduplication_id",
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
