# Generated by Django 3.1 on 2020-08-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_merge_20200818_1445"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS
            "userprofile_covid19triage_deduplication_id_d43bee39_like";
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS
            "userprofile_healthcheckuserprofile_msisdn_b48139f5_like";
            """,
            reverse_sql="",
        ),
    ]
