# Generated by Django 3.1 on 2020-08-18 13:39

from django.db import migrations


class RunNonAtomicSQL(migrations.RunSQL):
    def _run_sql(self, schema_editor, sqls):
        if schema_editor.connection.in_atomic_block:
            schema_editor.atomic.__exit__(None, None, None)
        super(RunNonAtomicSQL, self)._run_sql(schema_editor, sqls)


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0005_merge_20200818_1445"),
    ]

    operations = [
        RunNonAtomicSQL(
            sql="""
            DROP INDEX CONCURRENTLY IF EXISTS
            "userprofile_covid19triage_deduplication_id_d43bee39_like";
            """,
            reverse_sql="",
        ),
        RunNonAtomicSQL(
            sql="""
            DROP INDEX CONCURRENTLY IF EXISTS
            "userprofile_healthcheckuserprofile_msisdn_b48139f5_like";
            """,
            reverse_sql="",
        ),
    ]
