# Generated by Django 3.1.14 on 2022-05-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_auto_20200902_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="tbconnect_group_arm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("control", "Control"),
                    ("health_consequence", "Health Consequence"),
                    ("planning_prompt", "Planning Prompt"),
                    ("soft_commitment", "Soft Commitment"),
                    ("soft_commitment_plus", "Soft Commitment Plus"),
                ],
                max_length=22,
                null=True,
            ),
        ),
    ]
