# Generated by Django 3.1.8 on 2021-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_auto_20200902_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="hcs_study_a_arm",
            field=models.CharField(
                choices=[
                    ("C", "Control"),
                    ("T1", "Treatment 1"),
                    ("T2", "Treatment 2"),
                    ("T3", "Treatment 3"),
                    ("T4", "Treatment 4"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="hcs_study_b_arm",
            field=models.CharField(
                choices=[
                    ("C", "Control"),
                    ("T1", "Treatment 1"),
                    ("T2", "Treatment 2"),
                    ("T3", "Treatment 3"),
                    ("T4", "Treatment 4"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="hcs_study_c_arm",
            field=models.CharField(
                choices=[
                    ("C", "Control"),
                    ("T1", "Treatment 1"),
                    ("T2", "Treatment 2"),
                    ("T3", "Treatment 3"),
                    ("T4", "Treatment 4"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
    ]
