# Generated by Django 3.1.14 on 2022-05-17 11:23

from django.db import migrations, models
import functools
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_healthcheckuserprofile_research_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckuserprofile',
            name='activation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthcheckuserprofile',
            name='originating_msisdn',
            field=models.CharField(max_length=255, null=True, validators=[functools.partial(userprofile.validators._phone_number, *(), **{'country': 'ZA'})]),
        ),
    ]
