# Generated by Django 3.1.14 on 2022-07-06 13:08

from django.db import migrations, models
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_auto_20220517_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="city_name",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[userprofile.validators.geographic_coordinate],
            ),
        ),
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="street_name",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[userprofile.validators.geographic_coordinate],
            ),
        ),
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="suburb_name",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[userprofile.validators.geographic_coordinate],
            ),
        ),
    ]
