# Generated by Django 3.1.14 on 2022-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_auto_20220517_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheckuserprofile",
            name="tbconnect_group_arm_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
