# Generated by Django 3.1.14 on 2023-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0014_healthcheckuserprofile_tbconnect_group_arm_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheckuserprofile",
            name="tbconnect_group_arm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("control", "Control"),
                    ("soft_commitment_plus", "Soft Commitment Plus"),
                ],
                max_length=22,
                null=True,
            ),
        ),
    ]
