# Generated by Django 3.1.14 on 2023-10-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20231010_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
