# Generated by Django 3.1 on 2020-11-17 12:48

from django.db import migrations, models
import django.utils.timezone
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LNCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduplication_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('msisdn', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('age', models.CharField(choices=[('<18', '<18'), ('18-39', '18-39'), ('40-65', '40-65'), ('>65', '>65')], max_length=5)),
                ('cough', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('difficulty_breathing', models.BooleanField()),
                ('muscle_pain', models.BooleanField()),
                ('smell', models.BooleanField()),
                ('exposure', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], max_length=9)),
                ('tracing', models.BooleanField(help_text='Whether the Lifenet can contact the user')),
                ('completed_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=22)),
                ('follow_up_optin', models.BooleanField(default=False)),
            ],
            bases=(models.Model, django_prometheus.models.ExportModelOperationsMixin('model_name')),
        ),
    ]
