# Generated by Django 3.1 on 2020-11-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifenet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lncheck",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("eng", "English"), ("fr", "Français")],
                max_length=3,
                null=True,
            ),
        ),
    ]
