# Generated by Django 3.1 on 2020-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifenet", "0002_lncheck_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lncheck",
            name="exposure",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("not_sure", "Not Sure")],
                max_length=9,
            ),
        ),
    ]
