# Generated by Django 3.1.8 on 2021-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaccine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccineSuburb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=255)),
                ("municipality", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("suburb", models.CharField(max_length=255)),
                ("suburb_id", models.CharField(max_length=255)),
            ],
        ),
    ]
