# Generated by Django 3.1.14 on 2021-12-15 15:51

from django.db import migrations, models
import functools
import userprofile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_ref",
                    models.CharField(
                        help_text="The reference code for the Real411 complaint",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "msisdn",
                    models.CharField(
                        help_text="The phone number of the person who submitted the complaint",
                        max_length=255,
                        validators=[
                            functools.partial(
                                userprofile.validators._phone_number,
                                *(),
                                **{"country": "ZA"}
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this complaint was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When this complaint was last updated",
                    ),
                ),
            ],
        ),
    ]
